---
#This Playbook configures the mongos service of mongodb

- name: Create the mongos configuration file
  template: src=mongos.conf.j2 dest={{ mongodb_config_prefix }}/mongos.conf

- name: Start the mongos service
  shell: mongos --config {{ mongodb_config_prefix }}/mongos.conf

- name: pause
  pause: seconds=20

- name: copy the file for shard test
  template: src=testsharding.j2 dest=/tmp/testsharding.js

- name: copy the file enable  sharding
  template: src=enablesharding.j2 dest=/tmp/enablesharding.js
