---
# This Playbook would deploy the whole mongodb cluster with replication and sharding.

- hosts: all
  remote_user: snwbr
  become: yes
  gather_facts: yes
  
  roles:
  - role: common

- hosts: mongo_servers
  become: yes
  roles:
  - role: mongod

- hosts: mongoc_servers
  roles:
  - role: mongoc

- hosts: mongos_servers
  roles:
  - role: mongos

- hosts: mongo_servers
  tasks:
  - include: roles/mongod/tasks/shards.yml
