---
# This role deploys the mongod processes and sets up the replication set.

- name: create data directory for mongodb
  file: path={{ mongodb_datadir_prefix }}/mongo-{{ inventory_hostname }} state=directory owner=mongod group=mongod
  delegate_to: '{{ item }}'
  with_items: "{{ groups.replication_servers }}"

- name: create log directory for mongodb
  file: path=/var/log/mongo state=directory owner=mongod group=mongod

- name: create run directory for mongodb
  file: path=/var/run/mongodb state=directory owner=mongod group=mongod

- name: Create the mongodb startup file
  template: src=mongod.j2 dest=/etc/init.d/mongod-{{ inventory_hostname }} mode=0655
  delegate_to: '{{ item }}'
  with_items: "{{ groups.replication_servers }}"

- name: Create the mongodb.service file
  template: src=mongod.service.j2 dest=/usr/lib/systemd/system/mongod-{{ inventory_hostname }}.service mode=0644
  delegate_to: '{{ item }}'
  with_items: "{{ groups.replication_servers }}"

- name: Make sure config directory exists
  file: path={{ mongodb_config_prefix }} state=directory owner=mongod group=mongod
  delegate_to: '{{ item }}'
  with_items: "{{ groups.replication_servers }}"

- name: Create the mongodb configuration file
  template: src=mongod.conf.j2 dest={{ mongodb_config_prefix }}/mongod-{{ inventory_hostname }}.conf
  delegate_to: '{{ item }}'
  with_items: "{{ groups.replication_servers }}"
  
- name: Copy the keyfile for authentication
  copy: src=secret dest={{ mongodb_datadir_prefix }}/secret owner=mongod group=mongod mode=0400

- name: Set permissions for the keyfile
  shell: chcon system_u:object_r:mongod_var_lib_t:s0 {{ mongodb_datadir_prefix }}/secret

- name: Enable MongoDB service for automatic start
  shell: systemctl enable mongod-{{ inventory_hostname }}
  delegate_to: '{{ item }}'
  with_items: "{{ groups.replication_servers }}"
  
- name: Start the mongodb service
  command: creates=/var/lock/subsys/mongod-{{ inventory_hostname }} /etc/init.d/mongod-{{ inventory_hostname }} start
  delegate_to: '{{ item }}'
  with_items: "{{ groups.replication_servers }}"

- name: Create the file to initialize the mongod replica set
  template: src=repset_init.j2 dest=/tmp/repset_init.js

- name: Pause for a while
  pause: seconds=20

- name: Initialize the replication set
  shell: /usr/bin/mongo --port "{{ mongod_port }}" /tmp/repset_init.js
