---
# This playbook  deploys the mongodb configurationdb  servers

- name: Create data directory for mongoc configuration server
  file: path={{ mongodb_datadir_prefix }}/configdb state=directory owner=mongod group=mongod

- name: Create the mongodb startup file
  template: src=mongoc.service.j2 dest=/etc/systemd/system/mongoc.service mode=0644 seuser=system_u

- name: Create the mongo configuration server file
  template: src=mongoc.conf.j2 dest={{ mongodb_config_prefix }}/mongoc.conf

- name: Copy the keyfile for authentication
  copy: src=roles/mongod/files/secret dest={{ mongodb_datadir_prefix }}/secret owner=mongod group=mongod mode=0400 setype=mongod_var_lib_t

- name: Start the mongodb service
  systemd: name=mongoc state=started daemon_reload=yes enabled=yes

- name: pause
  pause: seconds=20

- name: add the admin user
  mongodb_user: database=admin name={{ mongo_admin_user }} password={{ mongo_admin_pass }} login_port={{ mongoc_port }} state=present
  ignore_errors: yes
